### ISSUE TITLE
Publish pre-built binaries and npm package

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/nepomuk#105]
Users should be able to install the Node.js bindings (and all tools in this project) via `npm install transit`. The common way we do this at Mapbox is as follows:
- [x] Bundle dependencies via Mason and install them before building the project
- [x] Let Travis build and publish binary dependencies for your `transit.node` Node.js bindings
  - [x] Follow [the docs for node-pre-gyp](https://github.com/mapbox/node-pre-gyp#node-pre-gyp) on how to build and publish binaries to our mapbox-node-binary s3 bucket  
  - [x] Follow [this PR](https://github.com/mapbox/node-cpp-skel/pull/41) for creating an aws user with permissions; you need to tokens to let Travis copy artifacts to the s3 bucket (use osrm's [ci.template.js](https://github.com/Project-OSRM/osrm-backend/tree/master/cloudformation) as starting point, the one in the PR has some issues ...) - you can publish locally first to see if it works; mbx auth, then follow the steps in the node-pre-gyp docs.
- [ ] Manually publish the Js part of the package to npm, `npm publish transit` -- Moved to https://github.com/mapbox/nepomuk/issues/108
- [x] Write releasing docs

Here's the Pull Request for node-or-tools https://github.com/mapbox/node-or-tools/pull/13

**Comment by MoKob** [comment]
I've moved the npm publish to the alpha-deploy. By now we got binaries on S3. Closing here.
