### ISSUE TITLE
High-level Architecture

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/nepomuk#3]
Here are some ideas wrt. the high-level architecture. I'd try and make sub-systems independent, providing clean interfaces between them. Communicating should happen via local UNIX socket or TCP / IP, allowing for patterns like pipeline, pub/sub, etc.

Here's a highly-contrived example, early on in the pipeline:

GTFS extractor sub-system: scrapes, fetches and parses feeds. Protobuf schema encodes data from feeds we can make use of. The sub-system passes the data further along to next sub-system. Communication could happen via Protobuf (encoding/decoding) and ZeroMQ for communication patterns. You can build an start multiple extractors for different sources, in different languages. All they have to do is encode their results in Protobuf and pass it on. Running multiple extractors is and should be possible.

Why?
- Language independence. We can write sub-systems in Python, Javascript, .. we don't care.
- Clear interfaces and interaction: strictly typed Protobuf interfaces, abstract communication patterns.
- Easy to scale up: just start more processes.

Here's an example from my LiDAR weekend project. It's using Protobuf to encode full 360 degree scans. Then we can use ZeroMQ for a Publisher / Subscriber abstraction: we can start multiple publishers (per laser) and subscribe to their scan data feed if we want to. We can decide on multiple publishers or subscribers.
- [Protobuf Schema](https://github.com/scanse/sweep-sdk/blob/334f74aab5eb716c17c466cb2718920ed1d88f09/libsweep/examples/net.proto)
- [CMakeLists.txt](https://github.com/scanse/sweep-sdk/blob/334f74aab5eb716c17c466cb2718920ed1d88f09/libsweep/examples/CMakeLists.txt#L32-L43)
- [PubSub Example](https://github.com/scanse/sweep-sdk/blob/334f74aab5eb716c17c466cb2718920ed1d88f09/libsweep/examples/net.cc#L20-L86)

Resources
- [Wiki](https://en.wikipedia.org/wiki/ZeroMQ)
- [ZeroMQ C++ API](http://api.zeromq.org/2-1:zmq-cpp)
- [Zero MQ Guide](http://zguide.zeromq.org/page:all)

**Comment by MoKob** [comment]
This is coming in #159

**Comment by MoKob** [comment]
Rest is ticketed in #154
